# Generated by Django 3.0.2 on 2020-04-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_verified'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='memer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memer_id', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
