# Generated by Django 3.0.2 on 2020-05-03 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.Comments'),
            preserve_default='True',
        ),
    ]
